version: '3.7'

services:
    http:
        build:
            context: .
            dockerfile: debian-php74-fpm.Dockerfile
        image: php:7.4-apache
        ports:
            - '8080:8080'
        volumes:
            - ./project:/var/www/html/project/
            - ./files/project.conf:/etc/apache2/sites-enabled/000-default.conf:ro
            - ./files/ports.conf:/etc/apache2/ports.conf:ro
            - ./files/fpm.conf:/etc/php/7.4/fpm/pool.d/www.conf:ro
            - ./files/hosts:/etc/hosts
    nginx:
        image: nginx
        volumes:
            - ./files/default_nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '80:80'